const clothingItems = 
[
  {
    "id": 1,
    "name": "Performance Training T-Shirt",
    "category": "Tops",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Black",
    "price": 29.99,
    "currency": "EUR",
    "stock": 120,
    "description": "Lightweight, breathable t-shirt designed for high-intensity workouts.",
    "full_description" : "Engineered for athletes who demand breathability and lightness, this black training tee is made from a soft polyester blend that pulls moisture away from the skin. Its ergonomic cut enhances freedom of movement, making it ideal for high-intensity workouts, from HIIT circuits to endurance runs. Available in sizes S–XL, it delivers a sleek, low-profile look while maintaining lasting comfort.",
    "delivery_time_days": 3,
    "shipping_fee": 4.99,
    "material": "Polyester blend"
  },
  {
    "id": 2,
    "name": "Flex Joggers",
    "category": "Bottoms",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Charcoal Grey",
    "price": 49.99,
    "currency": "EUR",
    "stock": 80,
    "description": "Slim-fit joggers with tapered legs and zippered pockets for convenience during training.",
    "full_description" : "These charcoal grey joggers combine urban style with training functionality. Their slim fit and tapered leg design give a tailored silhouette, while the cotton-poly blend ensures softness against the skin. Zippered pockets safely store small essentials like keys or a phone, making them equally practical for the gym, commute, or casual wear.",
    "delivery_time_days": 5,
    "shipping_fee": 4.99,
    "material": "Cotton-Polyester Blend"
  },
  {
    "id": 3,
    "name": "Seamless Long Sleeve Top",
    "category": "Tops",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Navy Blue",
    "price": 39.99,
    "currency": "EUR",
    "stock": 95,
    "description": "Seamless design with sweat-wicking technology for maximum comfort.",
    "full_description" : "Crafted with nylon-elastane, this top features a body-hugging, seamless construction that reduces chafing during dynamic workouts. Sweat-wicking fibers regulate temperature, keeping you dry and comfortable whether lifting, running, or layering under a jacket. The deep navy blue tone adds subtle sophistication to its technical performance.",
    "delivery_time_days": 4,
    "shipping_fee": 5.49,
    "material": "Nylon-Elastane"
  },
  {
    "id": 4,
    "name": "Lightweight Running Shorts",
    "category": "Bottoms",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Black/Red",
    "price": 34.99,
    "currency": "EUR",
    "stock": 60,
    "description": "4-inch shorts with built-in mesh lining for enhanced breathability.",
    "full_description" : "Perfect for warm-weather runs, these black and red shorts feature a 4-inch cut for unrestrictive stride length. The integrated mesh lining provides superior airflow and support, helping to prevent chafing over long distances. Quick-dry polyester fabric ensures comfort on even the most humid training days.",
    "delivery_time_days": 3,
    "shipping_fee": 3.99,
    "material": "Polyester"
  },
  {
    "id": 5,
    "name": "Performance Hoodie",
    "category": "Outerwear",
    "size_options": ["M", "L", "XL"],
    "color": "Olive Green",
    "price": 59.99,
    "currency": "EUR",
    "stock": 45,
    "description": "Durable hoodie ideal for workouts and everyday wear, featuring a kangaroo pocket.",
    "full_description" : "With its olive green finish and classic kangaroo pocket, this hoodie strikes the balance between workout durability and casual wearability. The cotton-poly blend fabric resists wear while maintaining softness, making it perfect for transitional weather. A must-have for warming up or post-training recovery.",
    "delivery_time_days": 6,
    "shipping_fee": 6.49,
    "material": "Cotton-Polyester Blend"
  },
  {
    "id": 6,
    "name": "Compression Leggings",
    "category": "Bottoms",
    "size_options": ["S", "M", "L"],
    "color": "Black",
    "price": 44.99,
    "currency": "EUR",
    "stock": 70,
    "description": "Second-skin fit with graduated compression for improved circulation.",
    "full_description" : "Designed for athletes who take recovery seriously, these leggings marry a skin-tight nylon-spandex blend with graduated compression technology. They improve circulation, reduce muscle fatigue, and provide a locked-in feel during high-output training. The sleek black look makes them perfect for layering or solo wear.",
    "delivery_time_days": 4,
    "shipping_fee": 4.49,
    "material": "Nylon-Spandex"
  },
  {
    "id": 7,
    "name": "Training Tank Top",
    "category": "Tops",
    "size_options": ["S", "M", "L", "XL"],
    "color": "White",
    "price": 24.99,
    "currency": "EUR",
    "stock": 130,
    "description": "Light and stretchy tank designed to keep you cool during intense training sessions.",
    "full_description" : "Lightweight and cut from breathable polyester, this white tank top excels in high sweat conditions. Its streamlined design and elastane-infused stretch ensure complete mobility, helping you stay cool and sharp during even the most intense sessions. A classic staple for any gym-goer.",
    "delivery_time_days": 2,
    "shipping_fee": 3.99,
    "material": "Polyester"
  },
  {
    "id": 8,
    "name": "Slim Fit Gym Shorts",
    "category": "Bottoms",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Grey Marl",
    "price": 29.99,
    "currency": "EUR",
    "stock": 100,
    "description": "Moisture-wicking gym shorts with an adjustable drawstring waistband.",
    "full_description" : "Functional yet stylish, these grey marl shorts combine cotton comfort with sweat-wicking polyester. An adjustable drawstring waistband provides a custom fit, making them versatile for lifting, cardio, or lounging. Their slim fit provides a neat modern silhouette without sacrificing flexibility.",
    "delivery_time_days": 3,
    "shipping_fee": 4.99,
    "material": "Cotton-Polyester"
  },
  {
    "id": 9,
    "name": "Training Zip Jacket",
    "category": "Outerwear",
    "size_options": ["M", "L", "XL"],
    "color": "Black",
    "price": 64.99,
    "currency": "EUR",
    "stock": 40,
    "description": "Lightweight zip jacket designed for warmth without restricting movement.",
    "full_description" : "This lightweight black jacket is engineered with a polyester-elastane blend for full range of motion. Featuring a sleek zip-through design, it offers warmth without bulk, making it the perfect layering piece before workouts or during outdoor training. Discreet logo detailing adds a polished finish.",
    "delivery_time_days": 5,
    "shipping_fee": 6.49,
    "material": "Polyester-Elastane"
  },
  {
    "id": 10,
    "name": "Performance Polo Shirt",
    "category": "Tops",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Dark Green",
    "price": 34.99,
    "currency": "EUR",
    "stock": 85,
    "description": "Stylish polo shirt built with breathable fabric for active and casual wear.",
    "full_description" : "Designed for crossover performance, this dark green polo shirt offers breathable comfort that transitions easily from gym floor to casual outings. The cotton-poly fabric keeps you cool, while the slim-fit cut enhances your athletic form. It’s sport utility with a polished, modern twist.",
    "delivery_time_days": 4,
    "shipping_fee": 5.49,
    "material": "Cotton-Polyester"
  },
  {
    "id": 11,
    "name": "Lightweight Windbreaker",
    "category": "Outerwear",
    "size_options": ["M", "L", "XL"],
    "color": "Steel Blue",
    "price": 74.99,
    "currency": "EUR",
    "stock": 35,
    "description": "Packable windbreaker with water-resistant finish for outdoor runs.",
    "full_description" : "A steel blue essential for unpredictable weather, this packable windbreaker boasts water resistance and breathability. Adjustable cuffs and a drawcord hem seal out the wind, while the featherlight polyester construction can be stuffed easily into a bag. Ideal for outdoor sprints, cycling, or everyday city wear.",
    "delivery_time_days": 6,
    "shipping_fee": 7.49,
    "material": "Polyester"
  },
  {
    "id": 12,
    "name": "Training Shorts 2-in-1",
    "category": "Bottoms",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Dark Grey",
    "price": 39.99,
    "currency": "EUR",
    "stock": 65,
    "description": "Training shorts with built-in compression layer for added support.",
    "full_description" : "Combining freedom and support, these dark grey shorts feature a breathable outer layer and a built-in compression liner that enhances muscle stability. The nylon-polyester blend keeps them light while offering durability. Ideal for athletes who need performance in both conditioning and strength training.",
    "delivery_time_days": 3,
    "shipping_fee": 4.99,
    "material": "Nylon-Polyester Blend"
  },
  {
    "id": 13,
    "name": "Oversized Training Tee",
    "category": "Tops",
    "size_options": ["M", "L", "XL"],
    "color": "Beige",
    "price": 27.99,
    "currency": "EUR",
    "stock": 75,
    "description": "Loose-fit tee for relaxed training sessions, with dropped shoulders.",
    "full_description" : "This beige oversized cotton tee is all about relaxed comfort. Dropped shoulders and a loose cut give athletes unrestricted movement while providing a laidback aesthetic. Breathable and soft, it’s a versatile choice for low-intensity sessions or recovery days.",
    "delivery_time_days": 2,
    "shipping_fee": 3.99,
    "material": "Cotton"
  },
  {
    "id": 14,
    "name": "Hybrid Joggers",
    "category": "Bottoms",
    "size_options": ["S", "M", "L", "XL"],
    "color": "Black",
    "price": 54.99,
    "currency": "EUR",
    "stock": 55,
    "description": "Versatile joggers with mesh panels for ventilation during workouts.",
    "full_description" : "For athletes who want ventilation without sacrificing performance, these black joggers feature mesh side panels, offering optimal airflow. The polyester-elastane fabric stretches with every movement, while the tapered ankle keeps the fit streamlined. A modern hybrid of performance wear and street-ready fashion.",
    "delivery_time_days": 5,
    "shipping_fee": 5.99,
    "material": "Polyester-Elastane"
  },
  {
    "id": 15,
    "name": "Everyday Crew Sweatshirt",
    "category": "Outerwear",
    "size_options": ["M", "L", "XL"],
    "color": "Heather Grey",
    "price": 49.99,
    "currency": "EUR",
    "stock": 90,
    "description": "Classic crew-neck sweatshirt for layering before and after training.",
    "full_description" : "With its heather grey cotton fleece, this sweatshirt provides warmth, softness, and timeless athletic style. The crew-neck design makes it a layering essential, perfect over training tees or tanks when commuting to the gym. It strikes the ideal balance between function and simplicity.",
    "delivery_time_days": 4,
    "shipping_fee": 5.49,
    "material": "Cotton Fleece"
  },
  {
    "id": 16,
    "name": "Training Baselayer Top",
    "category": "Tops",
    "size_options": ["S", "M", "L"],
    "color": "Black",
    "price": 42.99,
    "currency": "EUR",
    "stock": 60,
    "description": "Compression baselayer top engineered for moisture control and muscle support.",
    "full_description" : "Engineered from high-quality nylon, this black baselayer hugs the body with compression fit. It optimizes circulation, supports muscles, and regulates moisture during high-output sessions. Designed for layering under jerseys or jackets, it delivers top-to-bottom functionality in all conditions.",
    "delivery_time_days": 3,
    "shipping_fee": 4.99,
    "material": "Nylon"
  },
  {
    "id": 17,
    "name": "Cotton Training Shorts",
    "category": "Bottoms",
    "size_options": ["M", "L", "XL"],
    "color": "Stone Grey",
    "price": 24.99,
    "currency": "EUR",
    "stock": 105,
    "description": "Comfortable cotton shorts for casual training and lounging.",
    "full_description" : "Crafted from 100% cotton, these stone grey shorts provide ultimate breathability and casual comfort. Designed more for easy gym sessions and lounging than high-performance intensity, they embody laidback fitness wear with a classic minimalist look.",
    "delivery_time_days": 2,
    "shipping_fee": 3.49,
    "material": "100% Cotton"
  },
  {
    "id": 18,
    "name": "Full Zip Track Jacket",
    "category": "Outerwear",
    "size_options": ["M", "L", "XL"],
    "color": "Burgundy",
    "price": 69.99,
    "currency": "EUR",
    "stock": 50,
    "description": "Retro-inspired jacket with ribbed cuffs and collars, made for modern performance.",
    "full_description" : "Retro-inspired but technically updated, this burgundy track jacket is a nod to old-school athletic wear. Its ribbed cuffs and collar add vintage style, while the lightweight polyester construction makes it performance-ready. Perfect for workouts or streetwear styling.",
    "delivery_time_days": 5,
    "shipping_fee": 6.99,
    "material": "Polyester"
  },
  {
    "id": 19,
    "name": "Training Singlet",
    "category": "Tops",
    "size_options": ["S", "M", "L"],
    "color": "Dark Blue",
    "price": 22.99,
    "currency": "EUR",
    "stock": 110,
    "description": "Racerback singlet for unrestricted movement during weight training.",
    "full_description" : "This dark blue racerback singlet offers total freedom of movement. Ideal for weight training, the nylon-poly blend is sweat-wicking and breathable, ensuring maximum comfort while showing off shoulder mobility. A lightweight essential for serious lifters.",
    "delivery_time_days": 3,
    "shipping_fee": 3.99,
    "material": "Nylon-Poly Blend"
  },
  {
    "id": 20,
    "name": "Thermal Training Hoodie",
    "category": "Outerwear",
    "size_options": ["M", "L", "XL"],
    "color": "Black",
    "price": 79.99,
    "currency": "EUR",
    "stock": 30,
    "description": "Insulated hoodie with thermal lining for cold-weather outdoor training.",
    "full_description" : "Built for cold-weather training, this black thermal hoodie incorporates both polyester and fleece for warmth and breathability. The insulated lining traps heat without adding heaviness, making it indispensable for outdoor winter workouts. Durable, functional, and performance-driven, it’s an elite layer for athletes who train year-round.",
    "delivery_time_days": 7,
    "shipping_fee": 7.99,
    "material": "Polyester-Fleece"
  }
]

export default clothingItems